/**
 * Resource preload hints.
 *
 * IMPORTANT: We deliberately do NOT preload the raw .jpg files anymore.
 * The <Picture> component serves AVIF/WebP variants generated by
 * vite-imagetools, so preloading the .jpg would download a format the
 * browser will never use — wasting bandwidth and competing with the LCP
 * image for connection slots.
 *
 * The first hero slide already declares loading="eager" + fetchPriority="high"
 * inside CinematicHeroSlider, which gives the browser everything it needs
 * to prioritise the LCP correctly with the right format.
 */
export const Preload = () => null;
